version: "3.8"

services:
  mongo:
    image: mongo:6.0
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data_dev:/data/db

  frontend:
    build:
      context: .
      dockerfile: src/Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - ./src:/app/src
      - ./public:/app/public
      - ./index.html:/app/index.html
      - ./tsconfig.json:/app/tsconfig.json
      - ./tsconfig.app.json:/app/tsconfig.app.json
      - ./tsconfig.node.json:/app/tsconfig.node.json
      - ./vite.config.ts:/app/vite.config.ts
      - ./eslint.config.js:/app/eslint.config.js
      - ./components.json:/app/components.json
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
      - /app/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - backend

  backend:
    build:
      context: ./src/server
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3001"
    volumes:
      - ./src/server:/app
      - ./uploads:/app/uploads
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - MONGO_URI=mongodb://mongo:27017/apocalipssi
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - ollama
      - mongo

  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama
    pull_policy: always
    restart: unless-stopped
    entrypoint: sh -c "ollama serve & sleep 5 && ollama pull gemma:2b && tail -f /dev/null"

  # Service pour afficher les URLs
  urls-display:
    image: alpine:latest
    depends_on:
      - frontend
      - backend
      - ollama
    command: >
      sh -c "
      echo '🚀 ========================================';
      echo '🎉 Mode DÉVELOPPEMENT - Services démarrés !';
      echo '========================================';
      echo '';
      echo '📱 Frontend (Hot Reload): http://localhost:5173';
      echo '🔗 Backend API (Hot Reload): http://localhost:3001';
      echo '🤖 Ollama: http://localhost:11434';
      echo '';
      echo '💡 Modifications automatiquement rechargées !';
      echo '💡 Pour arrêter: docker-compose -f docker-compose.dev.yml down';
      echo '========================================';
      echo '';
      tail -f /dev/null
      "

volumes:
  ollama:
  mongo_data_dev:
